version: "3"
services:
   postgres:
    container_name: postgres
    restart: 'always'
    build: './postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "POSTGRES_MULTIPLE_DATABASES=${INSTANT_DB_DATABASE},${INSTANT_DB_USER},${INSTANT_DB_PASSWORD}"
      # not sure it is really necessary but it does not break anything ...
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./postgres/data:/data
    networks:
      - default
        
networks:
  default:
    external:
      name: instant      