version: "3"
services:
  pg:
    image: timescale/timescaledb-postgis:latest-pg11
    container_name: instant-pg
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data/pg_data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PGDATA=/var/lib/postgresql/data/pg_data
   
      
