version: "3"
services:

  instant-spring:
    image: asinatra/instant:0.1
    container_name: instant-spring
    depends_on:
     - pg
    ports:
      - "8080:7788"
  
  pg:
    image: timescale/timescaledb-postgis:latest-pg11
    container_name: instant-pg
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data/pg_data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${INSTANT_HOST}
      - PGDATA=/var/lib/postgresql/data/pg_data
    networks:
      - default
      

networks:
  default:
    external:
      name: instant