version: "3"
services:
  postgres:
    container_name: postgres
    restart: 'always'
    build: './postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${INSTANT_DB_DATABASE},${INSTANT_DB_USER},${INSTANT_DB_PASSWORD}
      - INSTANT_DB_DATABASE=${INSTANT_DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./postgres/data:/data
      - ./shared_dir:/geo_data
      - ./postgres/scripts:/scripts
    networks:
      - default

  osmworker:
    container_name: osmworker
    depends_on:
      - postgres
    build: './geospatial'
    environment:
      - INSTANT_DB_USER=${INSTANT_DB_USER}
      - PGPASS=${INSTANT_DB_PASSWORD}
      - INSTANT_DB_DATABASE=${INSTANT_DB_DATABASE}
    volumes:
      - ./shared_dir:/geo_data
      - ./geospatial/scripts:/scripts
    tty: true
    networks:
      - default

networks:
  default:
    external:
      name: instant